### ISSUE TITLE
New hombrew warning for apg formula

### ISSUE THREAD

**Issue by augmentedfourth** [jzaleski/homebrew-apg#2]
```
Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the jzaleski/jzaleski tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/jzaleski/homebrew-jzaleski/Formula/apg.rb:8
```

I ran `brew style --fix /usr/local/Homebrew/Library/Taps/jzaleski/homebrew-jzaleski/Formula/apg.rb` and it returned `1 file inspected, no offenses detected`. I'm not sure what's wrong, or what the warning message actually means.

**Comment by jzaleski** [comment]
This has been fixed with this commit: https://github.com/jzaleski/homebrew-jzaleski/commit/eec4493070e30d0f754d0e9ee2707d00073ef8d3. Thanks for surfacing this.

**Comment by augmentedfourth** [comment]
Warning is gone! Thanks for addressing this!
